pipelines:
  - name: my_pipeline_ct
    configuration:
      integrations:
          - name: s_art
      environmentVariables:
        readOnly:
          env1: cat
          env2:
            default: fat
            description: I am not fat
            values:
              - cat
              - dog
              - fat
    steps:
      - name: trigger_2
        type: Bash
        execution:
          onExecute:
            - printenv
            - echo "done"
            - write_output propertyCanvas "description=\"hello world\""
            - add_pipeline_variables prev_runid=$run_id
            - touch testreport.xml
            - save_tests testreport.xml
      - name: my_step_ct
        type: 
        execution:
          onStart:
            - echo "prepare for main execution"
            - printenv
        configuration:
          environmentVariables:
            step_env1:
              default: bar
              description: no bar 
              values:
                - foo
                - bar
                - koo
              allowCustom: true
            step_env2: flower
